List_Paises = ["Dolar EstadoUnidense (USD)",
               "Euro (EUR)",
               "Peso Colombiano (COP)",
               "Peso Argentino (ARS)",
               "Pesos Chilenos (CLP)",
               "Sol Peruano (PEN)",
               "Peso Uruguayo (UYU)",
               "Guaraní paraguayo (PYG)",
               "Real Brasileño (BRL)",
               "Dólar Canadiense (CAD)",
               "Peso Mexicano (MXN)",
               "Yen Japones (JPY)",
               "Yuan Chino (CNY)",
               "Libra esterlina (GBP)",
               "Afgani Afgano (AFN)",
               "Lek Albanés (ALL)",
               "Dram Armenio (AMD)",
               "Florín Antillano neerlandés (ANG)",
               "Kwanza Angoleño (AOA)",
               "Dólar Australiano (AUD)",
               "Lev Bulgaro (BGN)",
               "Dinar Bareiní (BHD)",
               "Franco Burundés  (BIF)",
               "Dólar Bermudeño (BMD)",
               "Dólar de Brunéi (BND)",
               "Boliviano (BOB)",
               "Dólar Bahameño (BSD)",
               "Ngultrum Butanés (BTN)",
               "Dólar Beliceño (BZD)",
               "Franco Congoleño (CDF)",
               "Dírham de los Emiratos Árabes Unidos (AED)",
               "Franco Suizo (CHF)",
               "Unidad de fomento Chileno (CLF)",
               "Peso Cubano (CUP)",
               "Escudo Caboverdiano (CVE)",
               "Corona Checa (CZK)",
               "Franco Yibutiano (DJF)",
               "Corona Danesa (DKK)",
               "Peso Dominicano (DOP),",
               "Dinar Argelino (DZD)",
               "Libra Egipcia (EGP)",
               "Libra malvinense (FKP)",
               "Lari georgiano (GEL)",
               "Cedi ghanés (GHS)",
               "Libra gibraltareña (GIP)",
               "Dalasi Gambiano (GMD)",
               "Franco guineano (GNF)",
               "Quetzal Guatemalteco (GTQ)",
               "Dólar Hongkonés (HKD)",
               "Lempira Hondureño (HNL)",
               "Kuna croata (HRK)",
               "Gourde Haitiano (HTG)",
               "Forinto húngaro (HUF)",
               "Rupia indonesia (IDR)",
               "Rupia india (INR)",
               "Dinar iraquí (IQD)",
               "Rial iraní (IRR)",
               "Corona islandesa (ISK)",
               "Libra de Jersey (JEP)",
               "Dólar Jamaiquino (JMD)",
               "Chelín keniano (KES)",
               "Som kirguís (KGS)",
               "Riel camboyano (KHR)",
               "Franco comorense (KMF)",
               "Won Norcoreano (KPW)",
               "Won Surcoreano (KRW)",
               "Dinar kuwaití (KWD)",
               "Kip laosiano (LAK)",
               "Libra Libanesa (LBP)",
               "Dólar liberiano (LRD)",
               "Dinar libio (LYD)",
               "Dírham marroquí (MAD)",
               "Leu moldavo (MDL)",
               "Denar macedonio (MKD)",
               "Kyat birmano (MMK)"
               "Tugrik mongol (MNT)",
               "Rupia de Mauricio (MUR)"
               "Rupia de Maldivas (MVR)",
               "Ringgit malayo (MYR)",
               "Metical mozambiqueño (MZN)",
               "Dólar namibio (NAD)",
               "Corona noruega (NOK)",
               "Rupia nepalí (NPR)",
               "Dólar neozelandés (NZD)",
               "Rial omaní (OMR)",
               "Balboa Panameño (PAB)",
               "Peso Filipino (PHP)",
               "Rupia pakistaní (PKR)",
               "Złoty Polaco (PLN)",
               "Leu rumano (RON)",
               "Dinar serbio (RSD)",
               "Rublo Ruso (RUB)",
               "Franco ruandés (RWF)",
               "Riyal saudí (SAR)",
               "Libra sudanesa (SDG)",
               "Corona sueca (SEK)",
               "Dólar de Singapur (SGD)",
               "Chelín somalí (SOS)",
               "Dólar surinamés (SRD)",
               "Baht tailandés (THB)",
               "Dinar tunecino (TND)",
               "Lira Turca (TRY)",
               "Dólar trinitense (TTD)",
               "Dolar Taiwanes (TWD)",
               "Chelín tanzano (TZS)",
               "Grivna Ucraniano (UAH)",
               "Som uzbeko (UZS)",
               "Đồng vietnamita (VND),"
               "Franco CFA de África Central (XAF)",
               "Dólar del Caribe Oriental (XCD)",
               "Franco CFA de África Occidental  (XOF)",
               "Franco CFP (XPF)",
               "Rial yemení (YER)",
               "Rand sudafricano (ZAR)",]